### ISSUE TITLE
Kafka 연결 오류 및 해결

### ISSUE THREAD

**Issue by kim946509** [twenty-naebae/gaebal-veryeasy#14]
### 🐞 버그 설명

- Kafka 연결 후 토픽 메세지를 발행하는 과정에서 오류가 발생하였습니다.

### ✅ 예상 결과

- 메세지가 정상적으로 보내질 것으로 예상

### ❗ 실제 결과

알려진 호스트가 없습니다 (kafka)

-------
kafka 호스트를 인식하지 못하였습니다.
이상한 점은 저는 로컬환경에서 테스트하기 때문에 환경변수에  `KAFKA_URL=localhost:9093 `을 넣어서 진행하였습니다. 즉, kafka라는 호스트는 사용한적이 없습니다.

### 💻 버그 시뮬레이션

- test하기 위해 테스트용 컨트롤러와 서비스를 만들어준 후 **로컬환경**에서 실행한뒤 테스트를 진행하였습니다.

### 📄 로그

```shell
java.net.UnknownHostException: 알려진 호스트가 없습니다 (kafka)
at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934) ~[na:na]
```

### 🌏 환경

- Docker-compose로 kafka 실행
- local환경에서 user-service 실행

### 🙋🏻 More

# 원인
원인은 kafka docker-compose 파일에 존재하였습니다.
```
kafka:
    environment: 
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
```
ADVERTISED_LISTENERS 는 Kafka 브로커가 클라이언트에게 자신의 연결 주소를 알려주는 설정입니다. 현재 설정에서는 "kafka:9092"라는 주소를 클라이언트에게 알려주고 있어서, 클라이언트는 이 주소로 연결을 시도합니다.

Docker 컨테이너 내부에서는 "kafka"라는 컨테이너명을 인식할 수 있지만, 로컬 환경에서 실행되는 Spring Boot에서는 이 호스트명을 인식할 수 없습니다.

# 해결책
```
KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094
KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
```
KAFKA의 외부 리스너가 내부리스너를 분리하여 설정하였습니다.
이렇게 설정하면 Docker 내부 통신은 "kafka:9092"를 사용하고, 외부 클라이언트는 "localhost:9093"을 사용합니다.
그렇기 때문에 로컬 환경에서는 KAFKA_URL=localhost:9093을 내부 컨테이너 환경에서는 KAFKA_URL=kafka:9092로 통신할 수 있습니다.
다만 아직 컨테이너 환경에서의 테스트는 진행해보지 못하였습니다.

# 수정된 docker-compsoe.yml파일 ( redis+zipkin+kafka+kafka-ui)
(kafka 수정 및 강의에서 사용하였던 kafka-ui를 추가하였습니다.) 서비스 모두가 공유하는 리소스를 하나로 묶었습니다. 따로 사용하시는 docker-compose파일이 있으시면 위에서 말씀드린부분만 수정해서 사용하시면 됩니다. (노션에도 넣어놨습니다!)
http://localhost:8081 에 접속하시면 됩니다.
```
version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      # 외부 포트 매핑: 호스트의 9093 포트를 컨테이너의 9093 포트로 매핑
      - "9093:9093"
    environment:
      # Kafka 프로세스 역할 설정: 브로커와 컨트롤러 역할 모두 수행
      KAFKA_CFG_PROCESS_ROLES: broker,controller

      # 노드 ID 설정: 클러스터 내에서 이 브로커를 식별하는 고유 ID
      KAFKA_CFG_NODE_ID: 1

      # 컨트롤러 쿼럼 투표자 설정: 컨트롤러 선출에 참여하는 노드 목록
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094

      # 리스너 설정: Kafka가 수신 대기할 프로토콜, 호스트, 포트 조합
      # INTERNAL: 컨테이너 내부 통신용 (9092)
      # EXTERNAL: 외부 클라이언트 통신용 (9093)
      # CONTROLLER: 컨트롤러 통신용 (9094)
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094

      # 공개 리스너 설정: 클라이언트에게 알려줄 연결 주소
      # 내부 클라이언트에게는 kafka:9092, 외부 클라이언트에게는 localhost:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      # 컨트롤러 리스너 이름 설정: 컨트롤러 통신에 사용할 리스너 지정
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # 리스너 보안 프로토콜 매핑: 각 리스너에 대한 보안 프로토콜 설정
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      # 브로커 간 통신에 사용할 리스너 이름 설정
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

      # 일반 텍스트 리스너 허용 설정: 보안되지 않은 연결 허용
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_data:/bitnami/kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - gaebal-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - gaebal-network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - gaebal-network

volumes:
  kafka_data:

networks:
  gaebal-network:
    external: true
```
